[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
dockerLayerCaching = false

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
numReplicas = 1

[services.redis]
serviceName = "redis"
type = "redis"
plan = "free"
