[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
dockerLayerCaching = false

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 5
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
numReplicas = 1
